#!/bin/bash

# forester is for when you have multiple branches off develop and you want to see where you stand amongst them
#
# you can bypass this script by doing:

# for branch in (topic/a topic/b wip/c); do
#   git log --stat --since=3days $branch >> /tmp/forester.txt \
#   && echo -e "\n\n=============\n$branch\n=============\n\n" >> /tmp/forester.txt
# done

# with the script, I just do `forester -b"topic wip"`
usage()
{
    cat <<- EOT

Usage: $0 [options] [--]

Options:
-h|help             Display this message
-d|days             Number days to go back -- defaults to 3
-o|outfile          Defaults to /tmp/forester.txt
-b|branch-prefix    Use -b"feature topic wip" to include branches beginning with those prefixes

EOT
}

while getopts ":hb:o:d:" opt
do
    case $opt in
        h|help          )  usage; exit 0;;
        d|days          )  DAYS=$OPTARG;;
        o|outfile       )  OUTFILE=$OPTARG;;
        b|branch-prefix )  BRANCH_PREFIX="$OPTARG";;
        \?              )  echo -e "\n  Option noexists : $OPTARG\n"; usage; exit 1;;
    esac
done
shift $(($OPTIND-1))

# how many days back?
DAYS=${DAYS:-"3"}

# what branches do you want to grab recent logs from?
BRANCH_PREFIX=${BRANCH_PREFIX:-feature}
OUTFILE=${OUTFILE:-"/tmp/forester.txt"}

echo "see forest for trees"
# fail if outside a git repository
git branch 1>/dev/null || { echo "you must be in a repository" ; exit 1 ;}

ARGS=
i=0
# loop thru git branches, adding to array (as ARGS[$i]) if we match a branch prefix
for branch in ${BRANCH_PREFIX[*]}; do
    [ $(git branch | cut -c'3-' | grep "$branch") ] && ARGS[$i]=$branch || continue;
    i=$((i+1))
done

if [ ${#ARGS} == 0 ]; then
{ echo "No branches matching $BRANCH_PREFIX" ; exit 1 ;}
fi

printline()
{
    echo
    printhrule $i
    echo $i
    printhrule $i
    echo
    git log --stat --pretty=oneline --since=${DAYS}days $1
}

printhrule()
{
    for j in `seq 1 ${#1}`
    do
        echo -n =
    done
    # adds a libe break
    echo 
}

for i in ${ARGS[@]}
do
    printline $i >> $OUTFILE    
done

