#!/bin/bash -xv

# forester is for when you have multiple branches off develop and you want to see where you stand amongst them
#
# how many days back?
DAYS=${1:-"3"}

# what branches do you want to grab recent logs from?
BRANCH_PREFIX=${2:-"feature"}
OUTFILE=${3:-"/tmp/forester.txt"}

# print statusline at the top
#echo -n "Forester: See the forest for the trees\n"  "$OUTFILE"

ARGS="$(git branch | cut -c'3-' | grep "^$BRANCH_PREFIX" | xargs)"

printline()
{
    ARG=$1
    echo "$ARG" >> $OUTFILE
    git log --stat --pretty=oneline --since=${DAYS}days $ARG
}


for i in ${ARGS[@]}
do
    printline $i >> $OUTFILE
    echo ============================================= >> $OUTFILE
done

